### ISSUE TITLE
MIME type ('application/octet-stream') is not executable

### ISSUE THREAD

**Issue by olgageletina** [jwagner/simplex-noise.js#45]
Hi there, 

Thanks for putting this awesome resource out there. I was hoping to use the 3.0.1 version in codepen but getting a MIME type ('application/octet-stream'). Here's the [link](https://codepen.io/geletina/pen/PoqgLgb). Version [2.4.0 seems to work fine](https://codepen.io/geletina/pen/abmrxPr), given a nearly identical implementation.

**Comment by jwagner** [comment]
Hey @olgageletina , Thanks for sharing this issue. The first link does not work for me 'This debug view expired.'. Can you update it? Should be able to have a look at this later today. :)

**Comment by olgageletina** [comment]
Thank you @jwagner!! Apologies, here's [the link](https://codepen.io/geletina/pen/PoqgLgb) and the [full error](https://animation-tests.s3.amazonaws.com/Screen+Shot+2022-01-18+at+10.16.02+PM.png) I'm getting.

**Comment by jwagner** [comment]
No worries @olgageletina . The issue doesn't seem to be with simplex-noise.js itself but rather with the config in cdnjs. Specifically this file here: https://github.com/cdnjs/packages/blob/master/packages/s/simplex-noise.json

Since simplex-noise 3 is now a module the best way to use it is to import it. I've updated the example pen to reflect this:
https://codepen.io/jwagner/pen/BNmpdm

Looking at it now it would probably be a good idea to add a few more nicer demos than this simple plasma effect as well. :)

Would be awesome if you can confirm that using the import is working for you.

**Comment by olgageletina** [comment]
Sweet, thank you @jwagner! For some reason when I import the simplex module it prevents [P5 from loading](https://codepen.io/geletina/pen/NWaVBaz). There are no errors in the console. In fact unless I remove the import statement completely (commenting it out doesn't work) P5 doesn't render. When I try to import P5 it throws an error. 

I filed an issue with codepen to see if it's on their side. The pen is for a class where most of the students are new to JS. So I was hoping to avoid the canvas scripting API for now.

**Comment by jwagner** [comment]
@olgageletina with the import statement your script runs in a module. This results in the setup function not being globally visible. A simple ```window.setup = setup;``` at the end of your script should resolve your issue. :)

**Comment by olgageletina** [comment]
Got it — appreciate your help!
